
pipeline {
    agent {
		node{
			label 'built-in'
			customWorkspace '/stage/asi/automations/tmp'	
		}
	}

    stages {		 
		stage('Environment') {
			steps {
				echo "MY_GIT_URL: ${env.MY_GITHUB}" 
				echo "params.Tag: ${params.Tag}"
			}
		}
		
		stage('Checkout') {
			steps {
				checkout scm
			}			
		}
		
        stage('Execution') {
            steps {
                script {
                    def response = sh(
                        script: """
                            ls -al
                        """,
                        returnStdout: true
                    ).trim() 
                    echo "response:${response}"               
                }
            }
        }
    }
}